name = "Wyrmzardry"
author = "Eset Kalenko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3dbb7bee09a16195a982e2743ab675deac82f1e5bb853d0a8ff93dae52547c86"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
