name = "Wyrmzardry"
author = "EsetKalenko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c741eb30018cf7d1621e31d3b47ec4f8d506846f8555214d928d1103fadd2be6"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
