name = "Wyrmzardry"
author = "EsetKalenko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2c2d9cf10ea1bedc38c1d31d663a606749ef9ed991ee33cfcb509bcd9a9d53c"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
