name = "Wyrmzardry"
author = "EsetKalenko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7822d2783c9693b29ebb034d20df79cee4ab9cbab5dc6e06e70bae1dd891e25"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
