name = "Wyrmzardry"
author = "EsetKalenko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbbd5896f2c8d7f16f063b917614e5506f4ca35bd8b97261dbb50726a08f4390"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
