name = "Wyrmzardry"
author = "Eset Kalenko"
version = "v1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca4099eb789ab6e4b04593bb6badba61c53c22a5c71487566e63cf080d2da483"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
